name: Keep Render Apps Alive
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install axios
      - name: Ping Render apps
        run: |
          node -e "
            const axios = require('axios');
            //(Ghub-AdityaDev2) (rvce.77- render) 
            //const urls = [
             // 'https://habit-tracker-b7ku.onrender.com/',
             // 'https://web-watcher-905d.onrender.com/index.html',
             // 'https://summerease-t3iu.onrender.com/',
             // 'https://jobtrail.onrender.com/'
           // ];

            // (Ghub-Valiant77)-(2324 -render) 
           // const urls = [
             // 'https://summerease-ovge.onrender.com',
             // 'https://web-watcher-gnod.onrender.com',
              //'https://habit-tracker-g92o.onrender.com'
            //];
            

             // (Ghub-AdityaDev704) (Dev-render) In use
            const urls = [
              'https://jobtrail-4l68.onrender.com',
              'https://summerease.onrender.com',
              'https://web-watcher.onrender.com',
              'https://habit-tracker-094s.onrender.com'
            ];

            
            async function pingAll() {
              for (const url of urls) {
                try {
                  console.log('Pinging ' + url + '...');
                  await axios.get(url);
                  console.log('Successfully pinged ' + url);
                } catch (error) {
                  console.error('Failed to ping ' + url + ': ' + error.message);
                }
              }
            }
            
            pingAll();
          "