name: Keep Render Apps Alive
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install axios
      - name: Ping Render apps
        run: |
          node -e "
            const axios = require('axios');
            //824 - rvce.77 render in use from 14/5/25 to 
            const urls = [
              'https://habit-tracker-b7ku.onrender.com/',
              'https://web-watcher-905d.onrender.com',
              'https://summerease-t3iu.onrender.com/'
            ];

            // 77-2324 render suspended
            //const urls = [
              //'https://summerease-ovge.onrender.com',
              //'https://web-watcher-gnod.onrender.com',
              //'https://habit-tracker-g92o.onrender.com'
           // ];
            

             // 248 -704 render suspended
            //const urls = [
              
            //];

            
            async function pingAll() {
              for (const url of urls) {
                try {
                  console.log('Pinging ' + url + '...');
                  await axios.get(url);
                  console.log('Successfully pinged ' + url);
                } catch (error) {
                  console.error('Failed to ping ' + url + ': ' + error.message);
                }
              }
            }
            
            pingAll();
          "